import { ConfigurableModuleBuilder } from "nestelia";
import {
  CacheModuleOptions,
  CacheOptionsFactory,
} from "./interfaces/cache-module.interface";

/**
 * Extra configuration options for the Cache module.
 *
 * @internal
 */
interface CacheModuleExtras {
  /**
   * Whether to register the module as global.
   *
   * @default false
   */
  isGlobal?: boolean;
}

/**
 * Configurable module class generated by ConfigurableModuleBuilder.
 *
 * This provides the base implementation for CacheModule with support for
 * static (register) and dynamic (registerAsync) configuration patterns.
 *
 * @internal
 */
export const { ConfigurableModuleClass, MODULE_OPTIONS_TOKEN } =
  new ConfigurableModuleBuilder<CacheModuleOptions>({
    moduleName: "Cache",
  })
    .setFactoryMethodName("createCacheOptions" as keyof CacheOptionsFactory)
    .setExtras<CacheModuleExtras>(
      { isGlobal: false },
      (definition, extras) => ({
        ...definition,
        global: extras.isGlobal,
      }),
    )
    .build();
